services:
  eureka-server:
    image: dockerakash18/eureka:$GITHUB_SHA
    build:
      context: ./eureka  # Path to your Eureka Server project
    ports:
      - "8760:8760"
    networks:
      - app-network

  user-service:
    image: dockerakash18/user-service:$GITHUB_SHA
    build:
      context: ./user-service  # Path to your User Service code
    ports:
      - "8082:8082"
    environment:
      #- SPRING_PROFILES_ACTIVE=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
