version: '3.8'

services:
  eureka-server:
    image: ${{ secrets.DOCKER_USERNAME }}/eureka:$GITHUB_SHA
    build:
      context: ./eureka  # Path to your Eureka Server project
    ports:
      - "8761:8761"
    networks:
      - app-network

  user-service:
    image: ${{ secrets.DOCKER_USERNAME }}/user-service:$GITHUB_SHA
    build:
      context: ./user-service  # Path to your User Service code
    ports:
      - "8082:8082"
    environment:
      #- SPRING_PROFILES_ACTIVE=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
