server:
  port: 8081

jwt:
  secret: YourSuperSecretKeyWhichIsLongEnough

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
            - name: JwtFilter
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=1
            - name: JwtFilter
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**
          filters:
            - StripPrefix=1
            - name: JwtFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
