# Use an official Maven image to build the app
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Use a lightweight OpenJDK 17 image to run the app
FROM openjdk:17-jdk-slim
COPY --from=build /app/target/user-service-1.0.jar /app/user-service-1.0.jar
ENTRYPOINT ["java", "-jar", "/app/user-service-1.0.jar"]