name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repo
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Eureka Service
        run: mvn clean package -DskipTests  --file eureka/pom.xml

      - name: Build Docker image for Eureka Service
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/eureka:$GITHUB_SHA ./eureka
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub using credentials stored in secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker eureka image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/eureka:$GITHUB_SHA  # Push the Docker image to Docker Hub

      - name: Build User Service
        run: mvn clean package -DskipTests  --file user-service/pom.xml

      - name: Build Docker image for User Service
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:$GITHUB_SHA ./user-service
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub using credentials stored in secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/user-service:$GITHUB_SHA  # Push the Docker image to Docker Hub

      - name: Deploy User Service to Docker (Local)
        run: |
          docker-compose down  # Stop any running containers
          docker-compose up -d  # Deploy the service using Docker Compose

      - name: List all containers
        run: docker ps -a

      - name: Wait for eureka-server
        run: |
          for i in {1..20}; do
            curl --fail http://localhost:8760 || sleep 3
            echo "Waiting for Eureka..." || true
          done

      - name: Show Docker Compose Logs
        run: docker-compose logs -f eureka &

      - name: Show live logs from user-service
        run: docker-compose logs -f user-service &

      - name: Wait for user-service to be ready
        run: |
          for i in {1..10}; do
            curl --fail http://localhost:8082/roles/hello && break || sleep 5
          done