name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repo

      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Set up JDK 17
        with:
          java-version: 17
          distribution: adoptopenjdk

      - name: Build User Service
        run: mvn clean package -DskipTests  # Build the User Service

      - name: Build Docker image for User Service
        run: docker build -t user-service:$GITHUB_SHA .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub using credentials stored in secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push user-service:$GITHUB_SHA  # Push the Docker image to Docker Hub

      - name: Deploy User Service to Docker (Local)
        run: |
          docker-compose down  # Stop any running containers
          docker-compose up -d  # Deploy the service using Docker Compose

      - name: Health Check for User Service
        run: |
          curl --fail http://localhost:8080/users/hello  # Health check to ensure the service is running